language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 0ba312e2-280b-4a6a-b331-441a9ea45052
  app: fast-ravine-97442
  on:
    repo: Laurn17/shipwhen-api
